# Generated by Django 4.1.3 on 2022-11-25 23:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=1)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ssn', models.CharField(max_length=11)),
                ('card', models.CharField(max_length=12)),
                ('hour', models.DateTimeField()),
                ('owner', models.CharField(max_length=14)),
                ('place', models.CharField(max_length=19)),
            ],
        ),
    ]
