# Generated by Django 4.1.3 on 2022-11-25 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='place',
            new_name='store',
        ),
    ]
